[package]
name = "async-tw-econ"
version = "0.8.0"
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = ["teeworlds", "console"]
categories = ["command-line-interface", "api-bindings"]
repository = "https://github.com/gerdoe-jr/async-tw-econ"
description = "Simple Rust library to use Teeworlds external console asynchronously"


[dependencies]
# Only needed for async_std support
async-std = { version = "1", optional = true }
futures = { version = "0.3", optional = true }

# Only needed for tokio support
tokio = { version = "1", features = ["net", "io-util"], optional = true }

[features]
default = ["tokio"]
tokio = ["dep:tokio"]
async-std = ["dep:async-std", "dep:futures"]
